version: "3.9"
name: gleam_api

services:
  app:
    container_name: api_app
    env_file:
      - .env
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis

  db:
    container_name: api_db
    env_file:
      - .env
    image: postgres:16
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:latest
    container_name: api_redis
    command: --port ${REDIS_PORT}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data

volumes:
  db:
  redis: