name = "radish"
version = "0.16.0"

description = "A Gleam client for Valkey, KeyDB, Redis and other tools with compatible APIs"

licences = ["Apache-2.0"]
links = [
    { title = "Gleam", href = "https://gleam.run" },
    { title = "KeyDB", href = "https://keydb.dev" },
    { title = "Valkey", href = "https://github.com/valkey-io/valkey" },
    { title = "Redis", href = "https://redis.io" },
]
repository = { type = "github", user = "massivefermion", repo = "radish" }

internal_modules = [
    "radish/tcp",
    "radish/resp",
    "radish/utils",
    "radish/client",
    "radish/encoder",
    "radish/decoder",
    "radish/command",
    "radish/command/*",
]

[dependencies]
gleam_erlang = "~> 0.33"
gleam_otp = "~> 0.16"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
mug = "~> 1.2"
lifeguard = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.2"
